<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SkiaSharp" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Najm.Core/Najm.Core.csproj" />
  </ItemGroup>
</Project>
